/* =========================================================
   EduGen EXPERT REASONING ENGINE V2
   Expert means reasoning, not inflated numbers.
   Every generated item requires at least three linked reasoning moves:
   interpret -> connect evidence/conditions -> evaluate -> conclude.
========================================================= */
const crypto = require("crypto");
const id = () => crypto.randomBytes(8).toString("hex");
const pick = (items, index) => items[((Number(index) || 0) % items.length + items.length) % items.length];

function make({ subject, grade, topic, family, question, answer, distractors, explanation, steps = 4 }) {
  return {
    id: id(), subject, grade, level: grade, topic, difficulty: "Expert",
    questionFamily: `expert-${family}`, questionType: "Multiple Choice",
    question, options: [answer, ...distractors], answer, correctAnswer: answer,
    explanation, learningObjective: `Analyze, connect, evaluate and justify conclusions in ${topic}.`,
    reasoningSteps: Math.max(4, steps), expertReasoning: true,
  };
}

function math(grade, topic, v) {
  const t = String(topic).toLowerCase();
  const common = [
    make({subject:"Mathematics",grade,topic,family:"domain-transfer",question:`An expression in ${topic} is simplified by cancelling a factor containing x. The simplified expression appears valid for every real x, but the original expression was undefined at one value. A student claims that the cancellation proves the original expression is defined there. What is the correct conclusion, and why?`,answer:"The cancelled value remains excluded because simplification preserves equality only on the original domain; the domain restriction must be carried through the argument.",distractors:["The value becomes valid because the factor disappeared.","The simplified form automatically defines the original expression everywhere.","The value is valid whenever substitution into the simplified form gives a number."],explanation:"First identify the original domain, then identify the restriction created by the denominator, then check what cancellation changes. Algebraic simplification cannot retroactively define an expression at a point where it was originally undefined."}),
    make({subject:"Mathematics",grade,topic,family:"proof-counterexample",question:`A claim about ${topic} is stated with the word “every.” You find one carefully constructed case that satisfies all stated conditions but contradicts the conclusion. A student says the case is unusual and should be ignored. What should an expert do?`,answer:"Use the valid counterexample to reject the universal claim, then identify which extra condition would be needed to make a restricted version true.",distractors:["Ignore the case because most examples support the claim.","Keep the claim because unusual cases cannot disprove general statements.","Replace the counterexample with an easier example that supports the claim."],explanation:"A universal claim must survive every admissible case. Expert reasoning then asks how the statement could be repaired rather than merely declaring it false."}),
    make({subject:"Mathematics",grade,topic,family:"equivalent-forms",question:`Two methods for a ${topic} problem produce different-looking results. Method A uses a transformation that is reversible only under a condition; Method B starts from the definition and never assumes that condition. Both calculations appear correct. What must be checked before deciding the answers are equivalent?`,answer:"Check whether every transformation is reversible under the original conditions and substitute the candidates into the original statement when necessary.",distractors:["Choose the longer derivation because it looks more rigorous.","Assume the two results are equivalent because both contain the same symbols.","Choose the first answer produced by the calculator."],explanation:"The expert traces the logical direction of each transformation, checks hidden restrictions, and verifies the final candidates in the original problem."}),
    make({subject:"Mathematics",grade,topic,family:"competing-models",question:`A ${topic} problem has two plausible models. Model A fits every observation given so far but requires an unstated assumption. Model B fits slightly less neatly but follows directly from the stated definitions. What should determine the final choice?`,answer:"The model whose assumptions are justified by the problem conditions should be preferred, even if the alternative initially looks simpler.",distractors:["Choose the model with the shortest calculation.","Choose the model that gives the most familiar answer.","Choose the model that matches the first observation only."],explanation:"Expert mathematical modelling separates fit from validity: a convenient model cannot be accepted if its essential assumption has not been established."}),
    make({subject:"Mathematics",grade,topic,family:"generalisation",question:`A student solves three examples in ${topic} and notices the same pattern. They want to state a theorem immediately. What additional reasoning is needed before the pattern can be accepted as a general result?`,answer:"Identify why the pattern follows from the defining conditions, or prove it for the full class of cases rather than relying on the examples alone.",distractors:["Use more examples until the pattern feels certain.","Choose the pattern with the nicest numerical values.","Assume that three matching examples establish a theorem."],explanation:"Examples provide evidence and may suggest a conjecture, but a general mathematical claim requires a valid argument covering all admissible cases."})
  ];
  if (t.includes("probability")) return pick([
    make({subject:"Mathematics",grade,topic,family:"conditional",question:`A screening test for a condition is positive. The condition is uncommon, the test detects most true cases, and a small fraction of healthy people also test positive. Which chain of reasoning is required to determine the probability that this particular positive result represents a true case?`,answer:"Combine the prevalence with the true-positive and false-positive rates, determine the numbers in each resulting group, and then divide true positives by all positives.",distractors:["Use only the percentage of true cases detected by the test.","Treat the positive result as proof because the test is accurate.","Ignore prevalence because it describes the population rather than the test."],explanation:"The required probability is conditional on a positive result. Base rate and both error rates must therefore be incorporated."}), ...common.slice(1)]);
  return pick(common, v);
}

function science(subject, grade, topic, v) {
  const t = String(topic).toLowerCase();
  const generic = [
    make({subject,grade,topic,family:"competing-hypotheses",question:`An investigation into ${topic} produces an observation that is consistent with two different explanations. A second measurement could support one explanation but weaken the other. What should the investigator do before accepting either explanation?`,answer:"State the predictions that differ between the explanations, control the relevant variables, and collect the measurement that can distinguish them.",distractors:["Choose the explanation that is most familiar.","Treat the first observation as proof of the first explanation.","Change several variables at once so more effects can be observed."],explanation:"Expert scientific reasoning separates observation from explanation and deliberately seeks discriminating evidence."}),
    make({subject,grade,topic,family:"causal-chain",question:`A change in ${topic} is followed by a second change and then a third. The first and third observations are correlated, but the middle process could provide the mechanism. What is the strongest conclusion?`,answer:"The observations suggest a possible causal chain, but the intermediate mechanism must be tested before claiming that the first change directly caused the third.",distractors:["Correlation proves the first change directly caused the third.","The middle process can be ignored because the final result is visible.","The third observation proves every step in the chain."],explanation:"A multi-step causal explanation requires evidence for the links between stages, not merely correlation between the first and last observations."}),
    make({subject,grade,topic,family:"control-variables",question:`Two groups are compared to investigate ${topic}. The measured outcome differs, but the groups also differ in temperature and starting condition. What is the main reasoning problem?`,answer:"The experiment cannot isolate the effect of the intended variable because the additional differences are possible confounding variables.",distractors:["The result is automatically valid because the outcome differs.","More variables always make an experiment stronger.","A control group is unnecessary whenever measurements are taken."],explanation:"First identify the intended independent variable, then check whether other conditions could explain the difference. A fair test isolates the causal factor."}),
    make({subject,grade,topic,family:"mechanism",question:`A proposed explanation for ${topic} accounts for the observed result but contradicts one established scientific principle. Another explanation accounts for the result and remains consistent with that principle. Which should be preferred?`,answer:"Prefer the explanation that accounts for the evidence while remaining consistent with established principles and stated conditions.",distractors:["Prefer the explanation with the more complicated wording.","Keep the first explanation because it was proposed first.","Ignore the established principle because observations always override reasoning."],explanation:"Experts reconcile evidence with mechanisms and constraints rather than accepting an explanation that requires a known principle to be violated."}),
    make({subject,grade,topic,family:"evidence-quality",question:`Three observations appear to support a conclusion about ${topic}, but one observation was obtained without a control and another could be explained by a second mechanism. What should an expert do before treating the conclusion as established?`,answer:"Evaluate the quality and independence of the evidence, remove alternative explanations, and seek controlled evidence that directly tests the conclusion.",distractors:["Count the observations and accept the majority.","Treat every observation as equally strong evidence.","Ignore the uncontrolled observation only if it disagrees with the conclusion."],explanation:"Evidence quality depends on control, relevance, independence and the ability to rule out competing explanations."})
  ];

  if (subject === "Physics") {
    const physics = [
      make({subject,grade,topic,family:"mechanism",question:`A moving object changes its motion after interacting with another object. The velocity changes even though the object's mass does not. Which reasoning best identifies the cause?`,answer:"The interaction produces a net force, and the resulting acceleration changes velocity; the mass determines how strongly the same net force changes the motion.",distractors:["Mass itself supplies the acceleration.","A change in velocity can occur without any interaction or net force.","The object's mass must change whenever its velocity changes."],explanation:"Connect interaction to net force, net force to acceleration, and acceleration to change in velocity. These are separate steps."}),
      make({subject,grade,topic,family:"energy-system",question:`A device receives energy, performs useful work, and becomes warm. A student says the useful output proves that all input energy became useful work. What should be concluded?`,answer:"The energy balance must include useful output and transfers such as heating; efficiency depends on the fraction of input energy transferred usefully.",distractors:["Heating means energy was destroyed.","Useful work and wasted energy cannot occur in the same system.","Efficiency is determined only by the amount of useful work."],explanation:"Track the complete energy pathway before evaluating efficiency. Energy is conserved even when part of it is transferred to less useful forms."}),
      make({subject,grade,topic,family:"circuit-model",question:`Two circuit arrangements use the same source and identical components but produce different brightness. Before attributing the difference to the lamps themselves, what sequence of reasoning is most appropriate?`,answer:"Compare the topology, determine how current and potential difference are distributed, calculate or infer power, then connect power to brightness.",distractors:["Assume the brighter lamp has a different material.","Compare brightness first and ignore the circuit arrangement.","Assume the source supplies identical current through every possible arrangement."],explanation:"The arrangement determines circuit relationships; those relationships determine power; power then explains the observable brightness."})
    ];
    return pick(physics, v);
  }
  if (subject === "Chemistry") {
    const chemistry = [
      make({subject,grade,topic,family:"particle-explanation",question:`A substance shows one observable property in the solid state and a different property after melting. Which reasoning best connects the observations to particle behaviour?`,answer:"Identify what remains the same at particle level, determine what changes in particle mobility or arrangement, and use that change to explain the new observable property.",distractors:["Assume melting creates a completely new substance in every case.","Explain the change only by saying the particles become hotter.","Ignore particle arrangement because only the final observation matters."],explanation:"A strong chemical explanation links macroscopic observations to changes in particle arrangement, energy and mobility."}),
      make({subject,grade,topic,family:"reaction-evidence",question:`A reaction produces gas, temperature changes, and a new colour appears. One student claims the colour alone proves a new substance formed. What should an expert do?`,answer:"Combine several independent observations and consider whether the complete evidence is consistent with a chemical change rather than relying on one observation alone.",distractors:["Accept the claim because colour always proves a reaction.","Reject the reaction because gases can never form physically.","Use only temperature because colour is never useful evidence."],explanation:"Expert reasoning weighs multiple observations and checks alternative physical explanations before concluding that a chemical change occurred."}),
      make({subject,grade,topic,family:"equilibrium",question:`A reversible chemical system changes after one condition is altered and later settles into a new stable composition. Which reasoning best explains the result?`,answer:"The disturbance changes the relative rates or equilibrium position, the system responds through both forward and reverse processes, and a new dynamic balance can then be established.",distractors:["The reverse reaction stops permanently.","Equilibrium means all particles stop reacting.","A new composition proves that the original reaction was irreversible."],explanation:"Dynamic equilibrium involves continuing opposing processes. A change in conditions can alter the balance without stopping molecular reactions."})
    ];
    return pick(chemistry, v);
  }
  if (subject === "Biology") {
    const biology = [
      make({subject,grade,topic,family:"inheritance",question:`A characteristic appears in an offspring even though neither parent visibly shows it. Before claiming that the characteristic arose spontaneously, what chain of reasoning should be considered?`,answer:"Determine whether the parents could carry alleles that do not produce the phenotype in them, then examine the possible allele combinations inherited by the offspring.",distractors:["Assume a new mutation must be responsible.","Conclude that inherited traits cannot skip a generation.","Assume the environment automatically changes the offspring's genes."],explanation:"Phenotype does not always reveal every allele carried by an individual. Carrier status and inheritance patterns must be considered before proposing mutation."}),
      make({subject,grade,topic,family:"ecosystem-cascade",question:`A predator population declines. Soon after, a prey population increases, vegetation decreases, and another ecosystem variable changes later. Which explanation is strongest?`,answer:"The observations may form a trophic cascade in which predator loss changes prey pressure, which changes vegetation and then affects downstream ecosystem processes.",distractors:["Each observation must have an unrelated cause.","Predators directly control every abiotic variable.","The vegetation change proves the predator ate the plants directly."],explanation:"The expert links population interactions through a causal chain while recognizing that the final variable should still be tested rather than assumed."}),
      make({subject,grade,topic,family:"homeostasis",question:`A physiological variable moves away from its normal range, a sensor detects the change, and an organ response later moves the variable back toward the range. What makes this an example of homeostasis?`,answer:"A deviation is detected and a coordinated response opposes the change, helping restore internal conditions toward a stable range.",distractors:["The body prevents every variable from changing at all.","The response increases the deviation until it becomes permanent.","Homeostasis means the external environment never changes."],explanation:"Homeostasis is dynamic regulation: variables fluctuate, sensors detect deviations and responses help restore a stable internal state."})
    ];
    return pick(biology, v);
  }
  return pick(generic, v);
}

function generateExpertQuestion({ subject, grade, topic, variationIndex = 0 }) {
  if (subject === "Mathematics") return math(grade, topic, variationIndex);
  return science(subject, grade, topic, variationIndex);
}

module.exports = { generateExpertQuestion };
