/* =========================================================
   EduGen EXPERT REASONING ENGINE V2
   Expert means reasoning, not inflated numbers.
   Every generated item requires at least four linked reasoning moves.
========================================================= */
const crypto = require("crypto");
const id = () => crypto.randomBytes(8).toString("hex");
const pick = (items, index) => items[((Number(index) || 0) % items.length + items.length) % items.length];

function make({ subject, grade, topic, family, question, answer, distractors, explanation, steps = 4 }) {
  return { id: id(), subject, grade, level: grade, topic, difficulty: "Expert", questionFamily: `expert-${family}`, questionType: "Multiple Choice", question, options: [answer, ...distractors], answer, correctAnswer: answer, explanation, learningObjective: `Analyze, connect, evaluate and justify conclusions in ${topic}.`, reasoningSteps: Math.max(4, steps), expertReasoning: true };
}

function math(grade, topic, v) {
  const common = [
    make({subject:"Mathematics",grade,topic,family:"domain-transfer",question:`An expression in ${topic} is simplified by cancelling a factor containing x. The simplified expression appears valid for every real x, but the original expression was undefined at one value. A student claims that the cancellation proves the original expression is defined there. What is the correct conclusion, and why?`,answer:"The cancelled value remains excluded because simplification preserves equality only on the original domain; the domain restriction must be carried through the argument.",distractors:["The value becomes valid because the factor disappeared.","The simplified form automatically defines the original expression everywhere.","The value is valid whenever substitution into the simplified form gives a number."] ,explanation:"First identify the original domain, then identify the restriction created by the denominator, then check what cancellation changes."}),
    make({subject:"Mathematics",grade,topic,family:"proof-counterexample",question:`A claim about ${topic} is stated with the word “every.” You find one carefully constructed case that satisfies all stated conditions but contradicts the conclusion. A student says the case is unusual and should be ignored. What should an expert do?`,answer:"Use the valid counterexample to reject the universal claim, then identify which extra condition would be needed to make a restricted version true.",distractors:["Ignore the case because most examples support the claim.","Keep the claim because unusual cases cannot disprove general statements.","Replace the counterexample with an easier example that supports the claim."],explanation:"A universal claim must survive every admissible case. Expert reasoning then asks how the statement could be repaired."}),
    make({subject:"Mathematics",grade,topic,family:"equivalent-forms",question:`Two methods for a ${topic} problem produce different-looking results. Method A uses a transformation that is reversible only under a condition; Method B starts from the definition and never assumes that condition. Both calculations appear correct. What must be checked before deciding the answers are equivalent?`,answer:"Check whether every transformation is reversible under the original conditions and substitute the candidates into the original statement when necessary.",distractors:["Choose the longer derivation because it looks more rigorous.","Assume the two results are equivalent because both contain the same symbols.","Choose the first answer produced by the calculator."],explanation:"Trace the logical direction of each transformation, check hidden restrictions, and verify candidates in the original problem."}),
    make({subject:"Mathematics",grade,topic,family:"competing-models",question:`A ${topic} problem has two plausible models. Model A fits every observation given so far but requires an unstated assumption. Model B fits slightly less neatly but follows directly from the stated definitions. What should determine the final choice?`,answer:"The model whose assumptions are justified by the problem conditions should be preferred, even if the alternative initially looks simpler.",distractors:["Choose the model with the shortest calculation.","Choose the model that gives the most familiar answer.","Choose the model that matches the first observation only."],explanation:"Separate fit from validity: a convenient model cannot be accepted if its essential assumption is unproved."}),
    make({subject:"Mathematics",grade,topic,family:"generalisation",question:`A student solves three examples in ${topic} and notices the same pattern. They want to state a theorem immediately. What additional reasoning is needed before the pattern can be accepted as a general result?`,answer:"Identify why the pattern follows from the defining conditions, or prove it for the full class of cases rather than relying on the examples alone.",distractors:["Use more examples until the pattern feels certain.","Choose the pattern with the nicest numerical values.","Assume that three matching examples establish a theorem."],explanation:"Examples suggest conjectures; a general mathematical claim requires an argument covering all admissible cases."})
  ];
  if (String(topic).toLowerCase().includes("probability")) {
    return pick([make({subject:"Mathematics",grade,topic,family:"conditional",question:`A screening test for a condition is positive. The condition is uncommon, the test detects most true cases, and a small fraction of healthy people also test positive. Which chain of reasoning is required to determine the probability that this particular positive result represents a true case?`,answer:"Combine the prevalence with the true-positive and false-positive rates, determine the numbers in each resulting group, and then divide true positives by all positives.",distractors:["Use only the percentage of true cases detected by the test.","Treat the positive result as proof because the test is accurate.","Ignore prevalence because it describes the population rather than the test."],explanation:"The probability is conditional on a positive result, so base rate and both error rates matter."}), ...common.slice(1)]);
  }
  return pick(common, v);
}

function science(subject, grade, topic, v) {
  const generic = [
    make({subject,grade,topic,family:"competing-hypotheses",question:`An investigation into ${topic} produces an observation consistent with two different explanations. A second measurement could support one explanation but weaken the other. What should the investigator do before accepting either explanation?`,answer:"State the predictions that differ between the explanations, control relevant variables, and collect the measurement that can distinguish them.",distractors:["Choose the explanation that is most familiar.","Treat the first observation as proof of the first explanation.","Change several variables at once so more effects can be observed."],explanation:"Separate observation from explanation and deliberately seek discriminating evidence."}),
    make({subject,grade,topic,family:"causal-chain",question:`A change in ${topic} is followed by a second change and then a third. The first and third observations are correlated, but the middle process could provide the mechanism. What is the strongest conclusion?`,answer:"The observations suggest a possible causal chain, but the intermediate mechanism must be tested before claiming that the first change directly caused the third.",distractors:["Correlation proves the first change directly caused the third.","The middle process can be ignored because the final result is visible.","The third observation proves every step in the chain."],explanation:"A multi-step causal explanation requires evidence for the links between stages."}),
    make({subject,grade,topic,family:"control-variables",question:`Two groups are compared to investigate ${topic}. The measured outcome differs, but the groups also differ in temperature and starting condition. What is the main reasoning problem?`,answer:"The experiment cannot isolate the effect of the intended variable because the additional differences are possible confounding variables.",distractors:["The result is automatically valid because the outcome differs.","More variables always make an experiment stronger.","A control group is unnecessary whenever measurements are taken."],explanation:"Identify the intended variable, then check whether other conditions could explain the difference."}),
    make({subject,grade,topic,family:"mechanism",question:`A proposed explanation for ${topic} accounts for the observed result but contradicts one established scientific principle. Another explanation accounts for the result and remains consistent with that principle. Which should be preferred?`,answer:"Prefer the explanation that accounts for the evidence while remaining consistent with established principles and stated conditions.",distractors:["Prefer the explanation with the more complicated wording.","Keep the first explanation because it was proposed first.","Ignore the established principle because observations always override reasoning."],explanation:"Experts reconcile evidence with mechanisms and constraints."}),
    make({subject,grade,topic,family:"evidence-quality",question:`Three observations appear to support a conclusion about ${topic}, but one observation was obtained without a control and another could be explained by a second mechanism. What should an expert do before treating the conclusion as established?`,answer:"Evaluate the quality and independence of the evidence, remove alternative explanations, and seek controlled evidence that directly tests the conclusion.",distractors:["Count the observations and accept the majority.","Treat every observation as equally strong evidence.","Ignore the uncontrolled observation only if it disagrees with the conclusion."],explanation:"Evidence quality depends on control, relevance, independence and the ability to rule out competing explanations."})
  ];
  if (subject === "Physics") {
    return pick([
      make({subject,grade,topic,family:"mechanism",question:`A moving object changes its motion after interacting with another object. The velocity changes even though its mass does not. Which reasoning best identifies the cause?`,answer:"The interaction produces a net force, the net force produces acceleration, and the acceleration changes velocity; mass determines the response to a given net force.",distractors:["Mass itself supplies the acceleration.","Velocity can change without any interaction or net force.","Mass must change whenever velocity changes."],explanation:"Connect interaction to net force, net force to acceleration, and acceleration to velocity change."}),
      make({subject,grade,topic,family:"energy-system",question:`A device receives energy, performs useful work, and becomes warm. A student says all input energy became useful work. What should be concluded?`,answer:"The energy balance must include useful output and transfers such as heating; efficiency is the fraction of input energy transferred usefully.",distractors:["Heating means energy was destroyed.","Useful work and wasted energy cannot occur together.","Efficiency is determined only by useful work."],explanation:"Track the complete energy pathway before evaluating efficiency."}),
      make({subject,grade,topic,family:"model-comparison",question:`Two models predict different motion for an object under the same conditions. Model A ignores resistance; Model B includes it. The measured motion falls between their predictions. What should an expert do next?`,answer:"Compare the size of the neglected resistance with the measurement uncertainty, then determine whether the intermediate result is consistent with a model that includes the relevant force.",distractors:["Choose Model A because it is simpler.","Choose Model B automatically because it has more terms.","Average the two predictions without examining the physical assumptions."],explanation:"Model choice requires comparing assumptions, evidence and uncertainty rather than complexity alone."})
    ], v);
  }
  if (subject === "Chemistry") {
    return pick([
      make({subject,grade,topic,family:"particle-explanation",question:`A substance shows one observable property in the solid state and a different property after melting. Which reasoning best connects the observations to particle behaviour?`,answer:"Identify what remains the same at particle level, determine what changes in particle mobility or arrangement, and use that change to explain the new observable property.",distractors:["Assume melting creates a completely new substance in every case.","Explain the change only by saying the particles become hotter.","Ignore particle arrangement because only the final observation matters."],explanation:"A strong explanation links macroscopic observations to particle arrangement, energy and mobility."}),
      make({subject,grade,topic,family:"reaction-evidence",question:`A reaction produces gas, temperature changes, and a new colour appears. One student claims the colour alone proves a new substance formed. What should an expert do?`,answer:"Combine independent observations and determine whether the complete evidence is consistent with a chemical change while considering physical alternatives.",distractors:["Accept the claim because colour always proves a reaction.","Reject the reaction because gases can never form physically.","Use only temperature because colour is never useful evidence."],explanation:"Expert reasoning weighs multiple observations and checks alternative explanations."}),
      make({subject,grade,topic,family:"equilibrium",question:`A reversible chemical system changes after one condition is altered and later settles into a new stable composition. Which reasoning best explains the result?`,answer:"The disturbance changes the relative forward and reverse processes, so the system responds and establishes a new dynamic balance.",distractors:["The reverse reaction stops permanently.","Equilibrium means all particles stop reacting.","A new composition proves the reaction was irreversible."],explanation:"Dynamic equilibrium involves continuing opposing processes."}),
      make({subject,grade,topic,family:"stoichiometric-reasoning",question:`Two reactants are mixed in amounts that are not in the exact reaction ratio. The reaction stops when one reactant is exhausted. What chain of reasoning identifies the limiting reactant?`,answer:"Convert each amount to moles, compare the available mole ratio with the balanced-equation ratio, identify which reactant is consumed first, then use it to determine the maximum product.",distractors:["Choose the reactant with the larger mass.","Choose the reactant with the smaller coefficient without using the actual amounts.","Assume both reactants are always consumed completely."],explanation:"Limiting-reactant reasoning requires the balanced equation and actual mole quantities."}),
      make({subject,grade,topic,family:"structure-property",question:`Two substances contain elements with similar total numbers of particles but have very different melting points. Which investigation gives the strongest explanation?`,answer:"Compare bonding type, particle arrangement and intermolecular or lattice forces, then connect those structural differences to the energy required to separate particles.",distractors:["Compare only the total number of particles.","Assume the substance with the higher melting point must have heavier atoms.","Use colour and state at room temperature as the complete explanation."],explanation:"Chemical properties emerge from structure and interactions, not from particle count alone."})
    ], v);
  }
  if (subject === "Biology") {
    return pick([
      make({subject,grade,topic,family:"inheritance",question:`A characteristic appears in an offspring even though neither parent visibly shows it. Before claiming that it arose spontaneously, what chain of reasoning should be considered?`,answer:"Determine whether the parents could carry alleles that do not produce the phenotype in them, then examine the possible allele combinations inherited by the offspring.",distractors:["Assume a new mutation must be responsible.","Conclude that inherited traits cannot skip a generation.","Assume the environment automatically changes the offspring's genes."],explanation:"Phenotype does not always reveal every allele carried by an individual."}),
      make({subject,grade,topic,family:"ecosystem-cascade",question:`A predator population declines. Soon after, a prey population increases, vegetation decreases, and another ecosystem variable changes later. Which explanation is strongest?`,answer:"The observations may form a trophic cascade in which predator loss changes prey pressure, which changes vegetation and then affects downstream ecosystem processes.",distractors:["Each observation must have an unrelated cause.","Predators directly control every abiotic variable.","Vegetation change proves the predator ate plants directly."],explanation:"Link population interactions through a causal chain while recognizing that downstream links should be tested."}),
      make({subject,grade,topic,family:"homeostasis",question:`A physiological variable moves away from its normal range, a sensor detects the change, and an organ response later moves it back toward the range. What makes this homeostasis?`,answer:"A deviation is detected and a coordinated response opposes the change, helping restore internal conditions toward a stable range.",distractors:["The body prevents every variable from changing at all.","The response increases the deviation until permanent.","Homeostasis means the external environment never changes."],explanation:"Homeostasis is dynamic regulation rather than perfect constancy."}),
      make({subject,grade,topic,family:"experimental-design",question:`A researcher concludes that a treatment improves plant growth because treated plants are taller. However, the treated group also received more water and light. What must happen before the treatment can be credited with causing the difference?`,answer:"Control water and light so the treatment is the main systematic difference, then compare outcomes using repeated measurements and appropriate controls.",distractors:["Accept the conclusion because the treated plants are taller.","Increase the treatment group size without controlling the other variables.","Remove all measurements except final height."],explanation:"Causal inference requires isolating the independent variable from confounding factors."}),
      make({subject,grade,topic,family:"mechanism-transfer",question:`A drug changes the activity of an enzyme and later changes the amount of a biological product. Which evidence would most strongly connect the drug to the final effect?`,answer:"Show that the drug changes enzyme activity under controlled conditions and that the predicted downstream change occurs when the enzyme pathway is altered.",distractors:["Measure only the final product and assume the enzyme caused it.","Use a single observation from one treated organism.","Ignore other pathways that could produce the same product."],explanation:"A mechanistic explanation is stronger when intermediate steps are experimentally linked to the final outcome."})
    ], v);
  }
  return pick(generic, v);
}

function generateExpertQuestion({ subject, grade, topic, variationIndex = 0 }) {
  if (subject === "Mathematics") return math(grade, topic, variationIndex);
  return science(subject, grade, topic, variationIndex);
}

module.exports = { generateExpertQuestion };
