const crypto = require("crypto");
const randomInt = (min, max) => Math.floor(Math.random() * (max - min + 1)) + min;
const randomItem = (items) => items[randomInt(0, items.length - 1)];
const shuffle = (items) => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i--) { const j = randomInt(0, i); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy; };
const id = () => crypto.randomBytes(8).toString("hex");
const GRADE_FACTOR = { JHS1: 1, JHS2: 1.25, JHS3: 1.5 };
const difficultyLevel = { Easy: 0, Medium: 1, Hard: 2, Expert: 3 };
function scale(grade, difficulty, base = 10) { return Math.max(2, Math.round(base * (GRADE_FACTOR[grade] || 1) * (1 + (difficultyLevel[difficulty] || 0) * 0.35))); }
function mcq({ question, answer, distractors, grade, topic, difficulty, family, explanation }) { return { id: id(), question, options: shuffle([answer, ...distractors]), answer, correctAnswer: answer, questionType: "Multiple Choice", subject: "Integrated Science", grade, level: grade, topic, difficulty, questionFamily: family, explanation, learningObjective: `Apply knowledge of ${topic}.` }; }
function makeMatter(grade, difficulty) { const mass = scale(grade, difficulty, 20); const volume = randomInt(2, Math.max(3, Math.round(mass / 2))); const density = +(mass / volume).toFixed(2); return mcq({ grade, topic: "Matter", difficulty, family: "application", question: `A sample has a mass of ${mass} g and a volume of ${volume} cm³. What is its density?`, answer: `${density} g/cm³`, distractors: [`${mass + volume} g/cm³`, `${+(mass * volume).toFixed(2)} g/cm³`, `${+(volume / mass).toFixed(2)} g/cm³`], explanation: `Density = mass ÷ volume = ${mass} ÷ ${volume} = ${density} g/cm³.` }); }
function makeMotion(grade, difficulty) { const time = randomInt(4, scale(grade, difficulty, 12)); const speed = randomInt(2, scale(grade, difficulty, 10)); const distance = speed * time; return mcq({ grade, topic: "Forces and Motion", difficulty, family: "calculation", question: `A cyclist travels at ${speed} m/s for ${time} s. How far does the cyclist travel?`, answer: `${distance} m`, distractors: [`${speed + time} m`, `${speed * time + speed} m`, `${Math.max(1, distance - time)} m`], explanation: `Distance = speed × time = ${speed} × ${time} = ${distance} m.` }); }
function makeEnergy(grade, difficulty) { const power = randomInt(20, scale(grade, difficulty, 100)); const time = randomInt(2, 8); const energy = power * time; return mcq({ grade, topic: "Energy", difficulty, family: "calculation", question: `A device operates at ${power} W for ${time} s. How much energy does it use?`, answer: `${energy} J`, distractors: [`${power + time} J`, `${power / time} J`, `${energy + power} J`], explanation: `Energy = power × time = ${power} × ${time} = ${energy} J.` }); }
function makeElectricity(grade, difficulty, family) { const voltage = randomInt(4, 24); const resistance = randomInt(2, 12); const current = +(voltage / resistance).toFixed(2); return mcq({ grade, topic: "Electricity", difficulty, family: family || "calculation", question: `A resistor of ${resistance} Ω is connected to a ${voltage} V source. What current flows through it?`, answer: `${current} A`, distractors: [`${voltage * resistance} A`, `${(resistance / voltage).toFixed(2)} A`, `${voltage + resistance} A`], explanation: `Using I = V/R, I = ${voltage}/${resistance} = ${current} A.` }); }
const CONCEPTS = {
  "Living and Non-Living Things": [["Which characteristic shows that an organism responds to its environment?", "Sensitivity", ["Digestion", "Rusting", "Melting"]]],
  "Cells and Simple Organisation": [["Which structure controls many activities of a typical cell?", "Nucleus", ["Cell wall", "Vacuole", "Cytoplasm"]]],
  "Cell Structure and Functions": [["Which organelle is mainly associated with aerobic respiration?", "Mitochondrion", ["Ribosome", "Cell wall", "Vacuole"]]],
  "Human Health and Nutrition": [["Which nutrient is mainly needed for growth and repair of body tissues?", "Protein", ["Water only", "Fibre only", "Mineral salts only"]]],
  "Plants and Their Functions": [["Which tissue transports water and mineral salts upward in a plant?", "Xylem", ["Phloem", "Stoma", "Petal"]]],
  "Matter and Changes of State": [["What happens to particles when a solid melts?", "They gain energy and move more freely", ["They stop moving", "They disappear", "They become atoms only"]]],
  "Energy Forms and Sources": [["Which source is renewable?", "Solar energy", ["Coal", "Petroleum", "Natural gas"]]],
  "Forces and Simple Machines": [["What is the main purpose of a simple machine?", "To make work easier by changing force or its direction", ["To create energy from nothing", "To eliminate friction completely", "To increase mass"]]],
  "The Solar System": [["Which object is the central star of our solar system?", "The Sun", ["Earth", "The Moon", "Mars"]]],
  "Water and Air": [["Which gas makes up the largest fraction of Earth's atmosphere?", "Nitrogen", ["Oxygen", "Carbon dioxide", "Hydrogen"]]],
  "Environment and Sanitation": [["Which practice helps reduce the spread of disease?", "Proper disposal of waste", ["Open dumping near water", "Sharing contaminated water", "Ignoring drainage"]]],
  "Particle Nature of Matter": [["Which statement about particles in matter is correct?", "They are in constant motion", ["They never move", "They have no spaces", "They exist only in gases"]]],
  "Mixtures and Separation": [["Which method separates an insoluble solid from a liquid?", "Filtration", ["Distillation only", "Chromatography only", "Evaporation of the solid"]]],
  "Chemical Changes": [["Which is evidence that a chemical change may have occurred?", "Formation of a new substance", ["Change of container", "Cutting paper", "Changing shape only"]]],
  "Reproduction in Plants and Animals": [["What is reproduction?", "Production of new individuals", ["Digestion", "Respiration", "Excretion"]]],
  "Human Body Systems": [["Which organ pumps blood around the body?", "Heart", ["Lungs", "Kidney", "Stomach"]]],
  "Food and Digestion": [["Where does most absorption of digested nutrients occur?", "Small intestine", ["Oesophagus", "Large intestine only", "Trachea"]]],
  "Heat and Temperature": [["Temperature is a measure related to the average...", "kinetic energy of particles", ["mass of the object", "number of atoms only", "volume only"]]],
  "Light and Sound": [["Sound needs what to travel through?", "A medium", ["A vacuum only", "Sunlight", "A magnetic field only"]]],
  "Ecology and Food Chains": [["What is a producer in a food chain?", "An organism that makes its own food", ["A primary consumer", "A decomposer only", "A parasite only"]]],
  "Atomic Structure and Elements": [["Which particle determines the atomic number of an element?", "Proton", ["Neutron", "Electron", "Molecule"]]],
  "Chemical Reactions": [["What is a catalyst?", "A substance that changes reaction rate without being permanently consumed", ["A reactant always used up", "A product of every reaction", "A source of heat only"]]],
  "Acids Bases and Salts": [["A solution with pH 3 is...", "acidic", ["neutral", "alkaline", "always concentrated"]]],
  "Cells and Organisation": [["What is the basic structural and functional unit of life?", "The cell", ["The organ", "The tissue only", "The organism only"]]],
  "Inheritance and Variation": [["What carries inherited information?", "Genes", ["Digestive enzymes", "Red blood cells", "Starch grains"]]],
  "Human Reproductive Health": [["Which practice helps prevent many sexually transmitted infections?", "Using appropriate barrier protection", ["Sharing needles", "Ignoring symptoms", "Sharing personal medical equipment"]]],
  "Respiration and Excretion": [["Which process releases usable energy from food in cells?", "Respiration", ["Excretion", "Transpiration", "Filtration"]]],
  "Force Work and Energy": [["Work is done on an object when a force causes...", "displacement in the direction of the force", ["no movement", "only a change of colour", "a change in temperature only"]]],
  "Electricity and Electromagnetism": [["What happens to the magnetic field around a current-carrying conductor when current increases?", "Its magnetic field becomes stronger", ["It disappears", "It becomes unrelated to current", "It always reverses direction"]]],
  "Waves and Sound": [["Which property of a sound wave is most directly associated with pitch?", "Frequency", ["Amplitude only", "Speed only", "Wavelength only"]]],
  "Earth Resources and Climate": [["Which human activity can increase atmospheric carbon dioxide?", "Burning fossil fuels", ["Photosynthesis", "Planting trees", "Using wind energy"]]],
  "Ecosystems and Conservation": [["Why is biodiversity important?", "It supports stable and resilient ecosystems", ["It eliminates all competition", "It prevents every disease", "It removes the need for conservation"]]],
};
function makeConcept(grade, topic, difficulty) { const rows = CONCEPTS[topic]; if (!rows) return null; const [question, answer, distractors] = randomItem(rows); return mcq({ grade, topic, difficulty, family: "concept", question, answer, distractors, explanation: `The correct answer is ${answer}.` }); }
function makeGeneric(grade, topic, difficulty) { return mcq({ grade, topic, difficulty, family: "application", question: `Which statement best describes the main idea studied under ${topic}?`, answer: `${topic} involves scientific principles, observations and evidence used to explain related natural phenomena.`, distractors: ["It is unrelated to evidence or observation.", "It applies only outside science.", "It cannot be investigated or tested."], explanation: `Questions about ${topic} should be answered using the scientific principles, evidence and relationships associated with the topic.` }); }
function makeDataQuestion(grade, difficulty) { const a = randomInt(2, 12), b = randomInt(2, 15); return mcq({ grade, topic: "Ecology and Food Chains", difficulty, family: "data-interpretation", question: `A survey records ${a} producers and ${b} primary consumers. How many organisms are in these two groups altogether?`, answer: `${a + b}`, distractors: [`${Math.abs(a - b)}`, `${a * b}`, `${a + b + 2}`], explanation: `${a} + ${b} = ${a + b}.` }); }
function makeInvestigation(grade, topic, difficulty) { return mcq({ grade, topic, difficulty, family: "investigation", question: `A learner investigates ${topic}. Which approach gives the most reliable scientific conclusion?`, answer: "Control relevant variables, collect repeatable measurements and use the evidence to support the conclusion.", distractors: ["Change several variables at once and use one observation.", "Choose the result expected before collecting data.", "Ignore measurements that disagree with the hypothesis."], explanation: "Reliable investigations control relevant variables, collect evidence systematically and base conclusions on the data." }); }
function generateJHSIntegratedScienceQuestion({ grade = "JHS1", topic, difficulty = "Medium", family }) {
  if (topic === "Matter" || topic === "Materials and Their Properties" || topic === "Matter and Changes of State") return family === "investigation" ? makeInvestigation(grade, topic, difficulty) : (topic === "Matter" ? makeMatter(grade, difficulty) : makeConcept(grade, topic, difficulty) || makeMatter(grade, difficulty));
  if (topic === "Forces and Motion") return makeMotion(grade, difficulty);
  if (topic === "Energy" || topic === "Energy Forms and Sources") return family === "investigation" ? makeInvestigation(grade, topic, difficulty) : (topic === "Energy" ? makeEnergy(grade, difficulty) : makeConcept(grade, topic, difficulty));
  if (topic === "Electricity" || topic === "Electricity and Electromagnetism") return makeElectricity(grade, difficulty, family);
  if (topic === "Ecology" || topic === "Ecology and Food Chains" || topic === "Ecosystems and Conservation") return family === "data-interpretation" ? makeDataQuestion(grade, difficulty) : (makeConcept(grade, topic, difficulty) || makeGeneric(grade, topic, difficulty));
  if (family === "investigation") return makeInvestigation(grade, topic, difficulty);
  return makeConcept(grade, topic, difficulty) || makeGeneric(grade, topic, difficulty);
}
function generateJHSIntegratedScienceQuestions({ grade = "JHS1", topic, difficulty = "Medium", count = 1 }) { const questions = [], seen = new Set(), families = ["concept", "application", "comparison", "cause-effect", "data-interpretation", "investigation", "misconception", "expert-reasoning"]; let attempts = 0; const maxAttempts = Math.max(100, count * 80); while (questions.length < count && attempts++ < maxAttempts) { const q = generateJHSIntegratedScienceQuestion({ grade, topic, difficulty, family: randomItem(families) }); if (!q) continue; const key = q.question.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim(); if (seen.has(key)) continue; seen.add(key); questions.push(q); } return questions; }
module.exports = { generateJHSIntegratedScienceQuestion, generateJHSIntegratedScienceQuestions };